### PR TITLE
Added 15.40 manifests

### PR DESCRIPTION
**Pull request by NotOfficer**
😀

### CODE REVIEW

**Comment by manlikesteve1111** [comment]
7Om3eXVxOTO5r1vO-ES5AE-fKKwg1w

**Comment by nqbin** [comment]
21yEPkbqhNy_ePUECE6oTHEmg0SIfw

**Comment by filipao123123** [comment]
WIYuFdTOCn_b67Mnik-Q0teZEIWd-Q

**Comment by red2pickle** [comment]
qSfz1yvL2a694c0e864a4e2aadd0229121cde46c

**Comment by tiredma** [comment]
Q8ph88FxJtDqcyJmvUaG6fHzDtjJZA

**Pull request merged**
